### ISSUE TITLE
[BUG] - Error with "OfflineUpdater.cmd"

### ISSUE THREAD

**Issue by ThomasParchmann** [n00b69/woa-beryllium#3]
### Description

OfflineUpdater.cmd throws an error shortly after showing "Pending" after installing the APP Packages. Also started the cmd as Admin. Used Driver release from 12.04.2024 - 20e60d6. Tested ESD Builds: Windows 11 22631.861 and 22000.318; windows 10 19045.2565. Uefi Screen File: ebbg.  Additionally: Tried to start device, boot into blue screen. Using "OfflineUpdater.cmd" to uninstall/reinstall drivers after that. Also didn't work.

PS: Awesome project and a very nice guide, easy to understand and follow!

### Reproduction steps

```bash
Exactly follow the guide "Installtion instructions" (with PC) until the "OfflineUpdater.cmd" step.
```

### Logs

```bash
[15:35:51][Information] DriverUpdater 2.1.2.0 - Cleans and Installs a new set of drivers onto a Windows Image
[15:35:51][Information] Copyright (c) 2017-2023, The LumiaWOA and DuoWOA Authors
[15:35:51][Information] https://github.com/WOA-Project/DriverUpdater

[15:35:51][Information] This program comes with ABSOLUTELY NO WARRANTY.
[15:35:51][Information] This is free software, and you are welcome to redistribute it under certain conditions.

[15:35:52][Information] The device has not been booted yet. Installing Board Support Package for the first time prior to first boot.
[15:35:52][Information] Reading definition file...
[15:36:08][Information] Installing new drivers...
[15:37:31][Information] [===========================100%===========================] 00:00:00.0
[15:37:31][Information] Enabling Cks
[15:37:32][Information] Reading definition file...
[15:37:33][Information] Installing App Framework Packages...
[15:38:27][Information] [===========================100%===========================] 00:00:00.0
[15:38:27][Information] Installing App Packages...
[15:38:28][   Error   ] Something happened!
[15:38:28][   Error   ] System.DivideByZeroException: Attempted to divide by zero.
   at DriverUpdater.Logging.ShowProgress(Int64 CurrentProgress, Int64 TotalProgress, DateTime startTime, Boolean DisplayRed, String StatusTitle, String StatusMessage)
   at DriverUpdater.DismProvider.InstallApplications(IEnumerable`1 applicationPaths)
   at DriverUpdater.Program.InstallApps(String Definition, String DriverRepo, String DrivePath, Boolean IsUpgrade)
   at DriverUpdater.Program.<>c__DisplayClass3_1.<DriverUpdaterAction>b__0(Object sender, DoWorkEventArgs e)
[15:38:28][Information] Done!
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 on the phone
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
You can ignore this error, the drivers are installed, just the appx packages (frameworks) are not.

You can install them manually by copying the beryllium\apps\IPA\Frameworks folder to your phone in Windows and opening them one by one.

**Comment by n00b69** [comment]
Oh, what does the blue screen say? Next to the big QR code it should say something like "Stop code: ACPI BIOS ERROR". Please tell me what it says.

**Comment by ThomasParchmann** [comment]
I think it was something with audio(?) I already used another install method now after it didn't work.

I tried to use the driver install version from here: https://renegade-project.tech/en/install 
I downloaded the older drivers, a 22621 build and used the install Method from there:
dism /apply-image /ImageFile:<path/to/install.esd> /index:1 /ApplyDir:X:\
The audio is not working but windows booted up as expected.

**Comment by n00b69** [comment]
You can try using OnlinUpdater now, just make sure you also update the UEFI file.

**Comment by ThomasParchmann** [comment]
Hey, i tried it and some blue screens appeared, but apparently they can simply be ignored. Everything works fine now, thank you!
